@startuml
(*)  --> "启动"
--> "读取缓存的注册地址"
--> "连接注册中心"
--> "拉取注册数据"
If "拉取成功" then
--> [Yes] "解析注册数据"
--> "异步注册监听数据项"
--> "根据拉取的注册数据构建服务模型"
--> "缓存服务模型到服务模型表"
--> "结束"
else
--> "打印错误日志"
--> "结束"
Endif
--> (*)
@enduml