@startuml
(*)  --> "请求服务"
--> "反序列化json格式string为map"
--> "根据请求参数里面的服务名称从服务\n模型表里提取服务模型"
--> "判断服务模型是否已经动态加载过"
If "没有加载" then
--> [Yes] "加载服务"
--> "转换请求的参数为class类实例"
else
--> [No] "转换请求的参数为class类实例"
Endif
--> "根据提供的zk地址或者dubbo服务的ip构建dubbo服务的reference"
--> "根据上面的reference和请求参数进行服务的请求"
--> "返回服务的结果"
-->(*)
@enduml