@startuml

User --> (注册中心) : 添加注册地址
(注册中心) --> (拉取注册数据) : 《包括》
(注册中心) --> (监听注册数据) : 《包括》
(注册中心) --> (转换注册数据) : 《包括》

newpage

User --> (创建服务)
(创建服务) --> (下载jar及相关依赖) : 《包括》
(创建服务) --> (动态加载jar) : 《包括》
(创建服务) --> (构建服务) : 《包括》
(创建服务) --> (存储服务) : 《包括》
(创建服务) <--- (更新服务) : 《继承》

newpage

User --> (服务请求)
(服务请求) --> (接收http请求) : 《包括》
(服务请求) --> (http格式转换dubbo格式) : 《包括》
(服务请求) --> (发起dubbo请求) : 《包括》
@enduml